/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import db.Conexao;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author wellersonelucas
 */
public class VerDocumento extends javax.swing.JFrame {


    boolean verAcao = false;
    /**
     * Creates new form ExcluirArquivo
     */
    public VerDocumento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanelPesquisar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextParaPesquisar = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jTexcluirarquivo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPesquisar.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquise para visualisar ");

        jTextParaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextParaPesquisarActionPerformed(evt);
            }
        });

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Para excluir o arquivo visualizado");

        jTexcluirarquivo.setText("Excluir arquivo");
        jTexcluirarquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexcluirarquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesquisarLayout = new javax.swing.GroupLayout(jPanelPesquisar);
        jPanelPesquisar.setLayout(jPanelPesquisarLayout);
        jPanelPesquisarLayout.setHorizontalGroup(
                jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                                .addGroup(jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextParaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                                                .addGap(239, 239, 239)
                                                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jTexcluirarquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelPesquisarLayout.setVerticalGroup(
                jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextParaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btPesquisar)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTexcluirarquivo)
                                .addContainerGap(255, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanelPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jTextParaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {


        try {
            Connection con = Conexao.fazConexao();
            String sql = "SELECT * FROM tb_documentos WHERE nome_autor = ? AND titulo = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, TelaLoggin.naofazer);
            ps.setString(2, jTextParaPesquisar.getText());

            ResultSet rs = ps.executeQuery();

            //verAcao = rs.next();
            if (rs.next()) {
                // Caso o usuário exista e as credenciais estejam corretas
                JOptionPane.showMessageDialog(null, "deu certo");
                sql = "SELECT caminho FROM tb_documentos WHERE nome_autor =? AND titulo = ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, TelaLoggin.naofazer);
                ps.setString(2, jTextParaPesquisar.getText());


                rs = ps.executeQuery();
                if (rs.next()) {
                    String caminho = rs.getString("caminho");
                    // Faça o que desejar com a variável caminho
                    System.out.println("Caminho do arquivo: " + caminho);
                    verAcao = true;

                    File arquivo = new File(caminho);

                    if (arquivo.exists()) {
                        try {
                            Desktop.getDesktop().open(arquivo);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    } else {
                        System.out.println("Arquivo PDF não encontrado!");
                    }




                } else {
                    System.out.println("Nenhum resultado encontrado.");
                }




            } else {
                // Caso o usuário não exista ou as credenciais estejam incorretas
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado");
            }

            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }



    }

    private void jTexcluirarquivoActionPerformed(java.awt.event.ActionEvent evt) {

        if(verAcao){
            try{Connection con = Conexao.fazConexao();
                String sql = "DELETE FROM tb_documentos WHERE nome_autor = ? and titulo =? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, TelaLoggin.naofazer);
                ps.setString(2, jTextParaPesquisar.getText());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Arquivo excluído com sucesso!");
            }
            catch (SQLException e) {
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null,"É necessário visualizar o arquivo para excluir");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JToggleButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelPesquisar;
    private javax.swing.JToggleButton jTexcluirarquivo;
    private javax.swing.JTextField jTextParaPesquisar;
    // End of variables declaration
}
